clc; 
clear all; 
close all; 
disp('enter the IIR filter design specification');
rp=input('enter the passband ripple:'); 
rs=input('enter the stopband ripple:'); 
wp=input('enter the passband freq:'); 
ws=input('enter the stopband freq:'); 
fs=input('enter the sampling freq:'); 
w1=2*wp/fs;
w2=2*ws/fs; 
[n,wn]=buttord(w1,w2,rp,rs,'s'); 
disp('Frequency response of IIR LPF is:');
[b,a]=butter(n,wn,'low','s'); 
w=0:.01:pi; 
[h,om]=freqs(b,a,w); 
m=20*log10(abs(h)); 
an=angle(h); 
figure,subplot(2101);
plot(om/pi,m); 
title('magnitude response of IIR filter is:'); 
xlabel('(a) Normalized freq. -->'); 
ylabel('Gain in dB-->'); 
subplot(2102);
plot(om/pi,an); 
title('phase response of IIR filter is:'); 
xlabel('(b) Normalized freq. -->'); 
ylabel('Phase in radians-->');
